import { Metadata } from "next/dist/lib/metadata/types/metadata-interface";

export const metadata: Metadata = {
  title: "Felipe Kadosh | Manager",
  description: "Generated by create next app",
};

export default function Manager() {
  return <main></main>;
}
