import { Metadata } from "next/dist/lib/metadata/types/metadata-interface";
import { UserButton } from "@clerk/nextjs";
import { auth } from "@clerk/nextjs/server";
import { redirect } from "next/navigation";
import { db } from "../_lib/prisma";
import { DataTable } from "../_components/ui/data-table";
import { productsColumns } from "./_columns";
import AddProductsButton from "../_components/AddProductsButton";
import SearchInput from "../_components/SearchInput";

export const metadata: Metadata = {
  title: "Felipe Kadosh | Manager",
  description: "Generated by create next app",
};

const Manager = async ({
  searchParams,
}: {
  searchParams?: {
    query?: string;
  };
}) => {
  const { userId } = await auth();
  if (!userId) {
    redirect("/login");
  }
  const query = searchParams?.query || "";
  const products = await db.products.findMany({
    where: {
      name: {
        contains: query,
        mode: "insensitive",
      },
    },
  });
  return (
    <main>
      <div className="flex items-center justify-center py-6">
        <div className="flex items-center w-[90%]">
          <div className="w-full flex justify-end items-center">
            <UserButton showName />
          </div>
        </div>
      </div>
      <div className="flex flex-col items-center">
        <div className="flex flex-col items-center w-[90%]">
          <div className="w-full flex justify-between items-center pb-4">
            <h1 className="md:text-2xl font-bold">Produtos</h1>
            <AddProductsButton />
          </div>
          <div className="w-full">
            <SearchInput />
          </div>
          <div className="w-full h-dvh mt-1">
            <DataTable columns={productsColumns} data={products} />
          </div>
        </div>
      </div>
    </main>
  );
};

export default Manager;
