import { Metadata } from "next/dist/lib/metadata/types/metadata-interface";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "../_components/ui/card";
import { Button } from "../_components/ui/button";
import { SignInButton } from "@clerk/nextjs";
import { auth } from "@clerk/nextjs/server";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Felipe Kadosh | Login",
  description: "Generated by create next app",
};

const Login = async () => {
  const { userId } = await auth();
  if (userId) {
    redirect("/manager");
  }
  return (
    <main>
      <section className="flex flex-col items-center justify-center w-dvw h-dvh">
        <div className="w-[90%] md:w-[30%]">
          <Card>
            <CardHeader>
              <CardTitle>Login</CardTitle>
              <CardDescription>Login in Manager</CardDescription>
            </CardHeader>
            <CardContent>
              <form>
                <div>
                  <div className="flex flex-col space-y-2">
                    <h1>Felipe Kadosh</h1>
                  </div>
                </div>
              </form>
            </CardContent>
            <CardFooter>
              <SignInButton>
                <Button className="w-full">Login</Button>
              </SignInButton>
            </CardFooter>
          </Card>
        </div>
      </section>
    </main>
  );
};

export default Login;
